version: '3'

vars:
  cli_aggregator: ./cli/main.go
  server_aggregator: ./server/main.go
  DOCKER_IMAGE_NAME: "dmytro-tkach/news-aggregator"
  DOCKER_IMAGE_TAG: "v1.0"
  DOCKERFILE_PATH: ".Dockerfile"
  DOCKER_PORT: "8443"
  SERVER_EXPOSE_PORT: "8443"
tasks:
  test:
    cmd: go test ./...
    desc: "Run tests"

  build_server:
    cmd: go build -o ./bin/news-aggregator-server {{.server_aggregator}}
    desc: "Build web-server version"

  build_cli:
    cmd: go build -o ./bin/news-aggregator-cli {{.cli_aggregator}}
    desc: "Build cli version"
# Usage: task run_server -- --fetch_interval=30s
  run_server:
    cmd: go run {{.server_aggregator}} {{.CLI_ARGS}}
    desc: "Run the web-server locally"
# Usage:task run_cli -- --sources=bbc_news --keywords=president
  run_cli:
    desc: "Run cli locally"
    cmd: go run {{.cli_aggregator}} {{.CLI_ARGS}}

  fmt:
    cmd: go fmt ./...
    desc: "Run go fmt"

  vet:
    cmd: go vet ./...
    desc: "Run go vet"

  mod_tidy:
    cmd: go mod tidy
    desc: "Run go mod tidy"

  docker_build:
    cmd: docker build -t {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}} .
    desc: "Build Docker image"

  docker_run:
    cmd: docker run --rm -p {{.DOCKER_PORT}}:{{.SERVER_EXPOSE_PORT}} {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}}
    desc: "Run Docker container locally"

  docker-push:
    desc: "Push the Docker image to the registry"
    cmd: docker push {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}}