version: '3'

env:
  DOCKER_IMAGE_NAME: "dmytro-tkach/news-aggregator"
  DOCKER_IMAGE_TAG: "v1.0"
  DOCKERFILE_PATH: ".Dockerfile"
  DOCKER_PORT: "8443"
  SERVER_EXPOSE_PORT: "8443"

tasks:
  test:
    cmd: go test ./...
    desc: "Run tests"

  build_server:
    cmd: go build -o ./bin/news-aggregator-server ./server/main.go
    desc: "Build web-server version"

  build_cli:
    cmd: go build -o ./bin/news-aggregator-cli ./cli/main.go
    desc: "Build cli version"

  fmt:
    cmd: go fmt ./...
    desc: "Run go fmt"

  vet:
    cmd: go vet ./...
    desc: "Run go vet"

  mod_tidy:
    cmd: go mod tidy
    desc: "Run go mod tidy"

  run_server:
    cmd: go run ./server/main.go
    desc: "Run the web-server locally"

  run_cli:
    cmd: go run ./cli/main.go
    desc: "Run cli locally"

  docker_build:
    cmd: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    desc: "Build Docker image"

  docker_run:
    cmd: docker run --rm -p $DOCKER_PORT:$SERVER_EXPOSE_PORT $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    desc: "Run Docker container locally"
