version: '3'

tasks:
  # Task to test Go code
  test:
    cmd: go test ./...
    desc: "Run tests"

  # Task to build server
  build_server:
    cmd: go build -o ./bin/news-aggregator-server ./server/main.go
    desc: "Build web-server version"

  # Task to build cli
  build_cli:
    cmd: go build -o ./bin/news-aggregator-cli ./cli/main.go
    desc: "Build cli version"

  # Task to run `go fmt`
  fmt:
    cmd: go fmt ./...
    desc: "Run go fmt"

  # Task to run `go vet`
  vet:
    cmd: go vet ./...
    desc: "Run go vet"

  # Task to run `go mod tidy`
  mod_tidy:
    cmd: go mod tidy
    desc: "Run go mod tidy"

  # Task to run the server locally
  run_server:
    cmd: go run ./server/main.go
    desc: "Run the web-server locally"

  # Task to run cli
  run_cli:
    cmd: go run ./cli/main.go
    desc: "Run cli locally"

  # A meta-task to run all checks
  check_all:
    cmds:
      - task: mod_tidy
      - task: fmt
      - task: vet
      - task: test
    desc: "Run all checks: mod tidy, fmt, vet, and tests"


  # Task to build Docker image
  docker_build:
    cmd: docker build -t news-aggregator:latest .
    desc: "Build Docker image"

   # Task to run Docker container locally
  docker_run:
    cmd: docker run --rm -p 8080:8080 news-aggregator:latest
    desc: "Run Docker container locally"
