apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-secret
  namespace: {{ .Values.namespace }}
stringData:
  AWS_SECRET_ACCESS_KEY: "{{ required "The secretKey is required." .Values.privateAccessKey}}"
  AWS_ACCESS_KEY_ID: "{{  required "The accessKey is required." .Values.accessKey}}"
  AWS_ACCOUNT: "{{ required "The account is required." .Values.aws_account_id }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-registry-helper-cm
  namespace: {{ .Values.namespace }}
data:
  AWS_REGION: "{{ .Values.aws_region }}"
  DOCKER_SECRET_NAME: "{{ .Values.docker_secret_name}}"