apiVersion: batch/v1
kind: CronJob
metadata:
  name: news-fetcher
  namespace: news-aggregator
spec:
  schedule: "0 12 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: news-fetcher
              image: dmytkach/news-fetcher:1.0.1
              volumeMounts:
                - name: news-volume
                  mountPath: /mnt/news
                - name: sources-volume
                  mountPath: /mnt/sources
              args:
                - -path_to_source=/mnt/sources/sources.json
                - -news_folder=/mnt/news
          restartPolicy: OnFailure
          volumes:
            - name: news-volume
              persistentVolumeClaim:
                claimName: news-aggregator-news-pvc
            - name: sources-volume
              persistentVolumeClaim:
                claimName: news-aggregator-sources-pvc
