version: '3'

vars:
  cronjob_aggregator: ./main.go
  cronjob_image_name: "dmytkach/news-fetcher"
  cronjob_image_tag: "1.0.2"
  cronjob_dockerfile_path: "cronjob/Dockerfile"
  cronjob_ecr_repository: "406477933661.dkr.ecr.us-west-1.amazonaws.com/dmytro-news-fetcher"

tasks:
  build:
    cmd: go build -o ./bin/fetch-news {{.cronjob_aggregator}}
    desc: "Build the News Fetcher app"

  run:
    cmd: go run {{.cronjob_aggregator}} {{.CLI_ARGS}}
    desc: "Run the News Fetcher app locally"

  docker_build:
    cmd: cd .. && docker build -t {{.cronjob_image_name}}:{{.cronjob_image_tag}} -f {{.cronjob_dockerfile_path}} .
    desc: "Build Docker image for the CronJob"

  docker_run:
    cmd: docker run --rm {{.cronjob_image_name}}:{{.cronjob_image_tag}}
    desc: "Run Docker container for the CronJob locally"

  docker_tag:
    cmd: docker tag {{.cronjob_image_name}}:{{.cronjob_image_tag}} {{.cronjob_ecr_repository}}:{{.cronjob_image_tag}}
    desc: "Tag Docker image with ECR repository URI"

  docker_push:
    desc: "Push the Docker image to ECR"
    cmd: docker push {{.cronjob_ecr_repository}}:{{.cronjob_image_tag}}

