apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.certificateName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certManager.tlsSecretName }}
  duration: {{ .Values.certManager.duration }}
  renewBefore: {{ .Values.certManager.renewBefore }}
  commonName: {{ .Values.certManager.commonName }}
  issuerRef:
    name: {{ .Values.certManager.issuerName }}
    kind: Issuer
