apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.app.name }}-news-fetcher
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name:  {{ .Values.app.name }}-news-fetcher
              image: {{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag }}
              volumeMounts:
                  - name: news-volume
                    mountPath: {{ .Values.persistentVolume.newsPath }}
                  - name: sources-volume
                    mountPath: {{ .Values.persistentVolume.sourcesPath }}
              args:
                - -path-to-source=/mnt/sources/sources.json
                - -news-folder=/mnt/news
          restartPolicy: OnFailure
          volumes:
            - name: news-volume
              persistentVolumeClaim:
                claimName: {{ .Values.persistentVolumeClaim.news }}
            - name: sources-volume
              persistentVolumeClaim:
                claimName: {{ .Values.persistentVolumeClaim.sources }}
