apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: news-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.news }}
        - name: sources-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.sources }}
        - name: tls-certificates
          secret:
            secretName: {{ .Values.certManager.tlsSecretName }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - "-port=:{{ .Values.containerPort }}"
            - "-path-to-source={{ .Values.persistentVolume.sourcesPath }}/sources.json"
            - "-news-folder={{ .Values.persistentVolume.newsPath }}"
            - "-tls-cert={{ .Values.certManager.tlsCertPath }}"
            - "-tls-key={{ .Values.certManager.tlsKeyPath }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          volumeMounts:
            - name: news-volume
              mountPath: {{ .Values.persistentVolume.newsPath }}
            - name: sources-volume
              mountPath: {{ .Values.persistentVolume.sourcesPath }}
            - name: tls-certificates
              mountPath: {{ .Values.certManager.tlsMountPath }}
              readOnly: true
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
