apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.news }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolume.newsPath }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.sources }}
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolume.sourcesPath }}
