apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.role.name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "create", "delete", "patch"]
  - apiGroups: ["apps/v1"]
    resources: ["deployments"]
    verbs: ["get", "create", "delete", "patch"]
