apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  accessKey: {{ .Values.accessKey | b64enc }}
  privateAccessKey: {{ .Values.privateAccessKey | b64enc }}
