{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.app.name }}-vpa
  namespace: {{ .Values.namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.app.name }}-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: "{{ .Values.app.name }}"
        minAllowed:
          cpu: {{ .Values.vpa.minAllowed.cpu }}
          memory: {{ .Values.vpa.minAllowed.memory }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxAllowed.cpu }}
          memory: {{ .Values.vpa.maxAllowed.memory }}
{{- end }}
