apiVersion: v1
kind: Secret
metadata:
  name: ecr-registry-helper-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  AWS_SECRET_ACCESS_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_ACCOUNT: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecr-registry-helper-cm
  namespace: {{ .Values.namespace }}
data:
  AWS_REGION: "us-west-1"
  DOCKER_SECRET_NAME: regcred