apiVersion: v2
name: aggregator-chart
description: A Helm chart for Kubernetes
type: application
version: 0.3.0
appVersion: "1.16.0"
dependencies:
  - name: cert-manager
    version: 1.15.3
    repository: https://charts.jetstack.io
  - name: vertical-pod-autoscaler
    version: 1.7.0
    repository: https://stevehipwell.github.io/helm-charts/