namespace: news-aggregator

app:
  name: news-aggregator

deployment:
  name: news-aggregator-deployment

replicas: 1

image:
  repository: 406477933661.dkr.ecr.us-west-1.amazonaws.com/dmytro-news-aggregator
  tag: 1.0.6


containerPort: 8443

serviceAccount:
  name: news-aggregator-sa

persistentVolume:
  news: news-aggregator-news-pv
  sources: news-aggregator-sources-pv
  size: 1Gi
  newsPath: /mnt/news
  sourcesPath: /mnt/sources

persistentVolumeClaim:
  news: news-aggregator-news-pvc
  sources: news-aggregator-sources-pvc

role:
  name: news-aggregator-role

roleBinding:
  name: news-aggregator-rolebinding

service:
  name: news-aggregator-service
  port: 443

cronjob:
  schedule: "0 12 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  image:
    repository: 406477933661.dkr.ecr.us-west-1.amazonaws.com/dmytro-news-fetcher
    tag: 1.0.2
certManager:
  certificateName: news-aggregator-cert
  tlsSecretName: news-aggregator-tls
  duration: 2160h
  renewBefore: 360h
  commonName: localhost
  issuerName: aggregator-cert-issuer
  tlsCertPath: /etc/tls/certs/tls.crt
  tlsKeyPath: /etc/tls/certs/tls.key
  tlsMountPath: /etc/tls/certs

issuer:
  name: aggregator-cert-issuer

resources:
  limits:
    cpu: "150m"
    memory: "192Mi"
  requests:
    cpu: "75m"
    memory: "96Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetUtilPercent: 80

vpa:
  enabled: true
  minAllowed:
    cpu: "30m"
    memory: "48Mi"
  maxAllowed:
    cpu: "150m"
    memory: "192Mi"

accessKey: ""
privateAccessKey: ""