apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-aggregator-deployment
  namespace: news-aggregator
  labels:
    app: news-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-aggregator
  template:
    metadata:
      labels:
        app: news-aggregator
    spec:
      containers:
        - name: news-aggregator
          image: dmytkach/news-aggregator:v1.0
          ports:
            - containerPort: 8443
