apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-aggregator-deployment
  namespace: news-aggregator
  labels:
    app: news-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-aggregator
  template:
    metadata:
      labels:
        app: news-aggregator
    spec:
      serviceAccountName: news-aggregator-sa
      containers:
        - name: news-aggregator
          image: dmytkach/news-aggregator:1.0.5
          ports:
            - containerPort: 8443
          args:
            - "-port=:8443"
            - "-cert=./server/certificates/cert.pem"
            - "-key=./server/certificates/key.pem"
            - "-path_to_source=/mnt/sources/sources.json"
            - "-news_folder=/mnt/news"
          volumeMounts:
            - name: news-volume
              mountPath: /mnt/news
            - name: sources-volume
              mountPath: /mnt/sources
      volumes:
        - name: news-volume
          persistentVolumeClaim:
            claimName: news-aggregator-news-pvc
        - name: sources-volume
          persistentVolumeClaim:
            claimName: news-aggregator-sources-pvc