version: '3'

vars:
  operator_image_tag: "v3"
  KUBECTL: "kubectl"
  ignore_not_found: "false"
  LOCALBIN: "$(pwd)/bin"
  CONTROLLER_GEN: "{{.LOCALBIN}}/controller-gen"
  operator_ecr_repository: "406477933661.dkr.ecr.us-west-1.amazonaws.com/dmytro-operator-controller-manager"

tasks:
  help:
    desc: "List all tasks with their descriptions"
    cmd: task --list

  manifests:
    desc: Generate WebhookConfiguration, ClusterRole and CustomResourceDefinition objects.
    cmd: '{{.CONTROLLER_GEN}} rbac:roleName=manager-role crd webhook paths=./... output:crd:artifacts:config=config/crd/bases'

  generate:
    desc: Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
    cmd: '{{.CONTROLLER_GEN}} object:headerFile="hack/boilerplate.go.txt" paths="./..."'

  fmt:
    desc: Run go fmt against code.
    cmd: go fmt ./...

  vet:
    desc: Run go vet against code.
    cmd: go vet ./...

  test:
    cmd: go test ./.../...
    desc: "Run tests"

  build:
    desc: Build manager binary.
    cmd: go build -o bin/manager cmd/main.go

  run:
    desc: Run a controller from your host.
    cmd: go run ./cmd/main.go

  docker_build:
    desc: Build docker image with the manager.
    cmd: docker build -t {{.operator_ecr_repository}}:{{.operator_image_tag}} .

  docker_push:
    desc: "Push the Docker image to ECR"
    cmd: docker push {{.operator_ecr_repository}}:{{.operator_image_tag}}

  deploy:
    desc: "Deploy controller to the K8s cluster specified in ~/.kube/config."
    deps: [ manifests ]
    cmd: |
      cd config/manager && kustomize edit set image controller={{.operator_ecr_repository}}:{{.operator_image_tag}}
      cd - 
      kustomize build config/default | kubectl apply -f -

  undeploy:
    desc: "Undeploy controller from the K8s cluster specified in ~/.kube/config."
    cmd: |
        kustomize build config/default | kubectl delete --ignore-not-found={{.ignore_not_found}} -f -