name: Deploy to ECR

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Task
        run: |
          sh -ci "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin


      - name: Check for Uncommitted Changes
        run: |
          if git diff --exit-code; then
            echo "No uncommitted changes, proceeding to build and push."
          else
            echo "Error: Uncommitted changes found, please commit them before push."
            exit 1
          fi

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Push images and charts to ECR
        run: |
          task push_to_ecr