name: Deploy to ECR

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Install Taskfile
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 406477933661.dkr.ecr.us-west-1.amazonaws.com

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push News-Aggregator-Server image to ECR
        run: |
          task docker_build
          task docker_tag
          task docker_push

      - name: Deploy Helm chart
        run: |
          task authenticate_helm
          task chart_package
          task chart_push

      - name: Push Cronjob Docker image
        working-directory: ./cronjob
        run: |
          task docker_build
          task docker_tag
          task docker_push

      - name: Push Operator-Manager image to ECR
        working-directory: ./operator
        run: |
          task docker_build
          task docker_tag
          task docker_push