name: release-please

on:
  push:
    branches:
      - master
      - feature/release-please
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run release-please
        id: create-version
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          target-branch: ${{ github.ref_name }}

      - name: Debug release-please output
        run: |
          echo "Release-please outputs:"
          echo "Version: ${{ steps.create-version.outputs.version }}"
          echo "Major: ${{ steps.create-version.outputs.major }}"
          echo "Minor: ${{ steps.create-version.outputs.minor }}"
          echo "Patch: ${{ steps.create-version.outputs.patch }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        if: ${{ steps.create-version.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: ${{ steps.create-version.outputs.release_created }}
        run: |
          IMAGE_TAG=$(echo "${{ steps.create-version.outputs.version }}" | sed 's/^v//')
          echo "Building Docker image with tag: ${IMAGE_TAG}"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/news-aggregator:${IMAGE_TAG} -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/news-aggregator:${IMAGE_TAG}}