# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install Task
        run: |
          sh -ci "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Run go mod tidy
        run: task mod_tidy

      - name: Run go fmt
        run: task fmt

      - name: Run go vet
        run: task vet

      - name: Run tests
        run: task test

      - name: Build server
        run: task build_server

      - name: Build CLI
        run: task build_cli