name: Go

on:
  pull_request:
    types: [ opened, ready_for_review ]
    branches:
      - "**"
  push:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      setup-done: ${{ steps.setup.outputs.setup-done }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install Task
        run: |
          sh -ci "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build CLI
        run: task build_cli

      - name: Build server
        run: task build_server

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: task test

  static-analysis:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run task for static analysis
        run: |
          task fmt
          task vet
          task mod_tidy

  check-formatting:
    runs-on: ubuntu-latest
    needs: static-analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify code formatting
        run: |
          git fetch
          git diff --exit-code > /dev/null
          if [ $? -ne 0 ]; then
            echo "Formatting changes detected. Please run 'task fmt' locally and commit the changes."
            exit 1
          else
            echo "No formatting changes detected."
          fi
